"""empty message

Revision ID: d7967088b4f6
Revises: 
Create Date: 2026-07-09 15:02:42.114990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7967088b4f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search_tra...',
    sa.Column('user_search_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('patron_id', sa.Integer(), nullable=True),
    sa.Column('search_term', sa.String(length=255), nullable=True),
    sa.Column('search_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['tb_artists.artist_id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['tb_patrons.patron_id'], ),
    sa.PrimaryKeyConstraint('user_search_id')
    )
    op.create_table('orders_purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('purchase_amt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_status', sa.Enum('pending', 'processing', 'shipped', 'delivered', 'completed', 'cancelled'), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('art_item_id', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('patron_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['art_item_id'], ['tb_arts.art_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['tb_artists.artist_id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['tb_patrons.patron_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.drop_table('order/purchase_details')
    op.drop_table('orders_purchases')
    op.drop_table('user_search_track')
    with op.batch_alter_table('messages_chats', schema=None) as batch_op:
        batch_op.alter_column('message_text',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('is_read',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('ratings_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.alter_column('rating_score',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'tb_arts', ['rated_art_id'], ['art_id'])
        batch_op.create_foreign_key(None, 'tb_artists', ['rated_artist_id'], ['artist_id'])

    with op.batch_alter_table('tb_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('admin_fullname',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('admin_email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('admin_password',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['admin_email'])

    with op.batch_alter_table('tb_art_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('art_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('art_type_name', sa.String(length=70), nullable=True))
        batch_op.drop_column('art-type-id')
        batch_op.drop_column('art-type-name')

    with op.batch_alter_table('tb_artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('artist_fname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('artist_lname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('artist_mail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('artist_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['artist_mail'])
        batch_op.create_foreign_key(None, 'state', ['artist_state_id'], ['state_id'])

    with op.batch_alter_table('tb_arts', schema=None) as batch_op:
        batch_op.alter_column('art_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('art_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.create_foreign_key(None, 'tb_artists', ['artist_art_id'], ['artist_id'])
        batch_op.create_foreign_key(None, 'tb_art_type', ['art_type_id'], ['art_type_id'])

    with op.batch_alter_table('tb_patrons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patron_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('patron_fname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('patron_lname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('patron_mail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('patron_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['patron_mail'])
        batch_op.create_foreign_key(None, 'state', ['patron_state_id'], ['state_id'])
        batch_op.drop_column('patron-id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_patrons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patron-id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('patron_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('patron_mail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('patron_lname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('patron_fname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('patron_id')

    with op.batch_alter_table('tb_arts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('art_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('art_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('tb_artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('artist_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('artist_mail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('artist_lname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('artist_fname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('tb_art_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('art-type-name', mysql.VARCHAR(length=75), nullable=True))
        batch_op.add_column(sa.Column('art-type-id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('art_type_name')
        batch_op.drop_column('art_type_id')

    with op.batch_alter_table('tb_admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('admin_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('admin_email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('admin_fullname',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('ratings_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('rating_score',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)
        batch_op.drop_column('comment')

    with op.batch_alter_table('messages_chats', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)
        batch_op.alter_column('message_text',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    op.create_table('user_search_track',
    sa.Column('user_search_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('artist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('patron_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('search_term', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('search_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_search_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders_purchases',
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patron_ord_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('artist_ord_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_date', mysql.DATETIME(), nullable=True),
    sa.Column('total_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_status', mysql.ENUM('pending', 'delivered'), nullable=True),
    sa.Column('delivery_address', mysql.VARCHAR(length=505), nullable=True),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order/purchase_details',
    sa.Column('purchase_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('purchase_amt', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('order_status', mysql.ENUM('pending', 'completed', 'cancelled'), nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('art_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stock_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('purchase_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orders_purchase')
    op.drop_table('user_search_tra...')
    # ### end Alembic commands ###
